### ISSUE TITLE
Distribute vi PyPI

### ISSUE THREAD

**Issue by amorphic** [FRC4564/Xbox#1]
Thanks for this handy module!

Would you be open to packaging it up properly and uploading it to PyPI? That would make it easy to incorporate into other projects.

I'd be happy to submit a PR for the packaging and take care of uploading to PyPI if it would help.

**Comment by FRC4564** [comment]
Hi amorphic,

I'm not familiar with what it takes to submit to PyPI, but if it is easy enough and you'd like to do it, please feel free to do so.

I was also thinking that I can add a 'wget' link to the readme to make it easy to grab the code.

Steve

**Comment by aabs7** [comment]
Can you add Joystick rumbling feature to your script? 
It is missing in there

**Comment by macaquedev** [comment]
Hello amorphic and FRC4564.

I have published this package to PyPI, listing FRC4564 as the maintainer and owner of the package and the code.

to install it, just run ```pip install xbox-remote```

**Comment by amorphic** [comment]
Thanks @macaquedev! :+1:
