### ISSUE TITLE
Opening this xbox.py closes file event14 and js0 in /dev/input

### ISSUE THREAD

**Issue by aabs7** [FRC4564/Xbox#3]
Can we have a way to not close file event14 and js0 in /dev/input

**Comment by FRC4564** [comment]
I don't have a simple answer for you on this issue.  My code relies on 'xboxdrv' which is grabbing hold of js0.  A quick read through the documentation for that driver suggests that adding the option `--evdev-no-grab` to the call will keep it from making that connection.  Just add this option to the xboxdrv subprocess call that's in the __init__ method of the Xbox class.  Here's the line of code I'm referring to showing the option added:

    self.proc = subprocess.Popen(['xboxdrv','--no-uinput','--detach-kernel-driver','--evdev-no-grab'], stdout=subprocess.PIPE)

Not sure if this will work for you, but certainly worth a try.  If that fails, you might glean something from the full docs on all of the [xboxdrv](https://pingus.seul.org/~grumbel/xboxdrv/xboxdrv.html) options.
